PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS Products (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Name TEXT NOT NULL,
    Price REAL NOT NULL,
    Description TEXT,
    ImageUrl TEXT,
    Category TEXT,
    InStock INTEGER NOT NULL DEFAULT 1,
    StockQuantity INTEGER NOT NULL DEFAULT 0,
    Tags TEXT,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME
);

CREATE TABLE IF NOT EXISTS Orders (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    OrderNumber TEXT NOT NULL UNIQUE,
    CustomerName TEXT NOT NULL,
    CustomerEmail TEXT NOT NULL,
    CustomerPhone TEXT,
    ShippingAddress TEXT,
    BillingAddress TEXT,
    Total TEXT NOT NULL,
    Status TEXT NOT NULL DEFAULT 'Pending',
    PaymentMethod TEXT NOT NULL DEFAULT 'Cash',
    PaymentStatus TEXT NOT NULL DEFAULT 'Pending',
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME
);

CREATE TABLE IF NOT EXISTS OrderItems (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    OrderId INTEGER NOT NULL,
    ProductId INTEGER,
    ProductName TEXT NOT NULL,
    Price TEXT NOT NULL,
    Quantity INTEGER NOT NULL DEFAULT 1,
    Subtotal TEXT NOT NULL,
    FOREIGN KEY (OrderId) REFERENCES Orders(Id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS OrderMeta (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    OrderId INTEGER NOT NULL,
    MetaKey TEXT NOT NULL,
    MetaValue TEXT,
    FOREIGN KEY (OrderId) REFERENCES Orders(Id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS SiteContents (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Key TEXT NOT NULL UNIQUE,
    Value TEXT,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS AdminUsers (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Username TEXT NOT NULL UNIQUE,
    PasswordHash TEXT NOT NULL,
    Email TEXT,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    LastLoginAt DATETIME
);

